### ISSUE TITLE
Windows version drag and drop exception.

### ISSUE THREAD

**Issue by yh4922** [onlyGuo/chatgpt_desktop#1]
Windows desktop version and a problem: When I click and drag a window, my mouse gets stuck, and the interface moves slowly. The mouse is released only after I finish dragging. Initially, I thought my computer was lagging, but I noticed that the operations within the software are smooth, so it should be an exceptional situation.

https://github.com/onlyGuo/chatgpt_desktop/assets/18353610/97e4461c-4545-4103-882e-fd1ad3e08303

**Comment by onlyGuo** [comment]
I have noticed this issue, it is a compatibility problem with the visual effects of the window on older versions of Windows. I will fix this issue in upcoming versions.

**Comment by onlyGuo** [comment]
fixed: https://github.com/onlyGuo/chatgpt_desktop/releases/tag/1.1
